config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # Scopes the path to sign in and sign out a user from omniauth-facebook
  # devise_scope :user do
  #   get 'sign_in', :to => 'devise/sessions#new', :as => :new_user_session
  #   get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  # end

  resources :activities do
      get 'map_location', on: :collection
  end
  get '/profile' => 'activities#profile'

  root 'activities#index'

  resources :locations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # GET /apartments/:apartment_id/map_locations
  get '/all_markers' => 'activities#show_all_activities'
  # POST for adding a user/participant to an activity.
  post '/participant/:activity_id' => 'participant#create'
  post '/participant/user'
  delete '/participant/:activity_id' => 'participant#destroy'
  
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :location, optional: false
  belongs_to :user, optional: true
  has_many :participation
  validates :terms_of_service, acceptance: true
  validates :location, presence: true

  accepts_nested_attributes_for :location, reject_if: :all_blank

  def organizer_name
    if self.user.present?
      "#{self.user.name}"
    else
      "Unknown"
    end
  end
  def organizer_email
    if self.user.present?
      "#{self.user.email}"
    else
      "Unknown"
    end

  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  load_and_authorize_resource
  # GET /activities
  # GET /activities.json
  def index
    if params[:location].present?
      @locations = Location.joins(:activities).near(params[:location], params[:distance], :units => :mi)  #.where(['activities.next_at > ?', Time.now])

      @activities = []
      @locations.each do |location|
        @activities += location.activities
      end
    elsif params[:search].present?
      @activities = Activity.search(params[:search])
    elsif params[:mine].present?
      #TODO laod the activities you are signed up for only
      @activities = current_user.participating_activities.where("next_at >= ?", 1.hour.ago)
    elsif params[:my_past].present?
      @activities = current_user.participating_activities.where("next_at < ?", 1.hour.ago)
    else
      @activities = Activity.all #.where(['activities.next_at > ?', Time.now])
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])
    @participant = User.joins(:participations).where("activity_id = ?", @activity.id)
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json

  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # This is a method to list all activities for the index map
  def show_all_activities
    @all_activities = Activity.all
    @hash = Gmaps4rails.build_markers(@all_activities) do |activity, marker|
      marker.lat(activity.location.latitude)
      marker.lng(activity.location.longitude)
      marker.infowindow("<strong>" + activity.name + "</strong><br><em>" + activity.location.address + "</em><br>")
    end
    render json: @hash.to_json
  end

  def profile
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:name, :user_id, :website, :description, :next_at, :location_id, :schedule, :requirement, :pricing, :fitness_level, :terms_of_service, location_attributes: [:id, :_destroy, :name, :address, :city, :state, :zip])
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<div class="container-fluid">
  <section class="row">
    <div class="col-sm-12">
        <h1>New Activity</h1>
        <%= form_for(activity) do |f| %>
        <% if activity.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

            <ul>
            <% activity.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>

        <%= f.hidden_field :user_id, value: current_user.id %>

        <div class="field">
          <%= f.label :website %>
          <%= f.text_field :website %>
        </div>

        <div class="field">
          <%= f.label :description %>
          <%= f.text_area :description %>
        </div>

        <div class="field">
          <%= f.label :next_at %>
          <%= f.datetime_select(:next_at, ampm: true) %>
        </div>

        <div class="field location_id_box">
          <%= f.label :location_id %>
          <%= f.collection_select(:location_id, Location.all, :id, :name, include_blank: true) %>
        </div>

        <%= link_to 'Add New Location', "#", id: 'new_location_form' %>
        <div class="location_subform hide">
          <%= f.fields_for :location, Location.new do |fl| %>
            <div class="field">
              <%= fl.label :location_name %>
              <%= fl.text_field :name %>
            </div>

            <div class="field">
              <%= fl.label :address %>
              <%= fl.text_field :address %>
            </div>

            <div class="field">
              <%= fl.label :city %>
              <%= fl.text_field :city %>
            </div>

            <div class="field">
              <%= fl.label :state %>
              <%= fl.text_field :state %>
            </div>

            <div class="field">
              <%= fl.label :zip %>
              <%= fl.text_field :zip %>
            </div>

          <% end %>
        </div>

        <div class="field">
          <%= f.label :schedule %>
          <%= f.text_area :schedule %>
        </div>

        <div class="field">
          <%= f.label :requirement %>
          <%= f.text_area :requirement %>
        </div>

        <div class="field">
          <%= f.label :fitness_level %>
          <%= f.select :fitness_level, ['Beginner', 'Intermediate', 'Advanced', 'All Levels Welcome'] %>
        </div>

        <div class="field">
          <%= f.label :pricing %>
          <%= f.text_field :pricing %>
        </div>

        <div class="actions terms">
          <%= f.label :terms_of_service %>
          <%= f.check_box :terms_of_service %> By agreeing to FindFits terms of service, FindFit is granted the right to use, reproduce, publish, translate and distribute your content in any existing and future media.  You also grant FindFit the right to sub-license these rights, and the right to bring an action for infringement of these rights.</span>
          <br><br>
          <%= f.submit %>
        </div>
      <% end %>
      <p><%= link_to 'Back', activities_path, class: "lg-link" %></p>
    </div>
  </section>
</div>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

app/views/activities/index.html.erb
<section class="row welcome">
  <div class="col-sm-12">
    <h1>Welcome to FindFit!</h1>
    <h2>A Fitness Group Connector</h2>
  </div>
</section>

<section class="row searchmap">
  <aside class="col-sm-12 col-lg-4 left-search">
    <h3>What is FindFit?</h3>
    <p>FindFit connects like-minded fitness enthusiasts by giving people the ability to create a fitness group or join an existing fitness group.</p>

    <%= form_tag(activities_path, :method => "get") do %>
      Search Map by Distance
      <%= label :distance, "Miles:" %>
      <%= select_tag :distance, options_for_select([[1, 1], [5, 5], [10, 10], [15, 15], [20, 20]]) %>

      <%= label :location, "From:" %>
      <%= text_field_tag :location, params[:location], placeholder: 'Address, City, State Zip' %>

      <%= submit_tag "Search By Distance", class: 'btn btn-default' %>
    <% end %>
    <br>
    Or Search Map by Activity Information
    <br>
    <%= form_tag(activities_path, :method => "get") do %>
        <%= label :search, "Activity Search:" %>
        <%= text_field_tag :search, params[:search], placeholder: 'Activity' %>
        <%= submit_tag "Search By Info", :name => nil, class: 'btn btn-default' %>
    <% end %>
    <br>
    <%= form_tag(activities_path, :method => "get") do %>
        <%= submit_tag "Click To View My Activities", name: "mine", class: 'view-activities btn btn-default' %>
    <% end %>

    <%= form_tag(activities_path, :method => "get") do %>
        <%= submit_tag "Click To View My Past Activities", name: "my_past", class: 'btn btn-default' %>
    <% end %>
  </aside>

  <aside class="col-sm-12 col-lg-8 right-map">
    <div id="activity_map" data-activity-id="0">Google Map will Appear Here</div>
  </aside>
</section>
<!-- end map section -->

<section class="row activityinfo">
  <article class="col-sm-12 table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Organizer Name</th>
          <th>Description</th>
          <th>Location</th>
          <th>Schedule</th>
          <th>Next at</th>
          <th>Participation</th>
        </tr>
      </thead>

      <tbody>
        <% @activities.each do |activity| %>
          <tr class='activity' data-lat='<%= activity.location.latitude %>' data-lng='<%= activity.location.longitude %>'>
            <td class='name'><%= link_to activity.name, activity_path(activity) %></td>
            <td class='organizer_name'><%= activity.organizer_name %></td>
            <td class='description'><%= activity.description %></td>
            <td class='location'><%= activity.location.try(:name) %></td>
            <td class='schedule'><%= activity.schedule %></td>
            <td class='next_at'><%= activity.next_at.try(:strftime, "%B %-d, %Y | %l:%M %P") %></td>

            <!--if the current user has a particiaption record that has the activity id of this activity -->

            <% if current_user.participations.where("activity_id = ?", activity.id).count > 0 %>
            <td id="participate"><%= link_to 'Remove', "/participant/#{activity.id}", method: :delete, data: { confirm: 'Are you sure?' }  %></td>
            <% else %>
            <td id="participate" class="sign_up"><%= link_to 'Sign Up', "/participant/#{activity.id}", method: :post, data: { confirm: 'Are you sure?' }  %></td>
            <% end %>
            <% if can? :manage, activity %>
            <td><%= link_to 'Delete', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </article>
  <article class="row">
    <div class="col-sm-12">
      <p>
        <%= link_to 'Create New Activity', new_activity_path, class: "lg-link" %>
      </p>
    </div>
  </article>
</section>

app/views/activities/new.html.erb
<%= render 'form', activity: @activity %>

app/views/activities/show.html.erb
<div class="container-fluid activity" data-lat='<%= @activity.location.latitude %>' data-lng='<%= @activity.location.longitude %>'>
  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <div class="show_header activity_title">
        <h1 class="name"><span class='name'><%= @activity.name %></span></h1>
      </div>
    </div>
    <div class="col-sm-1"></div>
  </div>

  <div class="row row-flex row-flex-wrap">
    <div class="col-sm-1"></div>
        <div class="col-sm-5 flex-col">
            <div class="media flex-grow">
              <div class="media-left">
                <a href="#" class="pop">
                  <img class="thumbnail" src="<%= @activity.location.image %>" alt="..." style="width: 75px; height 75px;">
                </a>
                <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-body">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <img src="" class="imagepreview" style="width: 100%;" >
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="media-body activity-info">
                <div>
                <% if @activity.location %>
                <h3 class="media-heading activity-info-text">Location: <span class="location"><%= @activity.location.name %></span></h3>
                <p class="activity-info-text">
                  <strong>Address:</strong>
                  <%= @activity.location.full_address %>
                </p>
                <p class="activity-info-text">
                  <strong>Fitness Level:</strong>
                  <%= @activity.fitness_level %>
                </p>
                <p class="activity-info-text">
                  <strong>Pricing:</strong>
                  <%= @activity.pricing %>
                </p>
                <p class="activity-info-text">
                  <strong>Requirements:</strong>
                  <%= @activity.requirement %>
                </p>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-5 flex-col">
          <div class="media flex-grow">
            <div class="media-left">
              <a href="#" class="pop">
                <img class="thumbnail" src="<%= @activity.user.image %>" alt="..." style="width: 75px; height 75px;">
              </a>
              <div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-body">
                      <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                      <img src="" class="imagepreview" style="width: 100%;" >
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="media-body activity-info">
              <h3 class="media-heading activity-info-text">Organizer: <%= @activity.organizer_name %>
              </h3>
              <p class="activity-info-text">
                <strong>Website:</strong>
                <span class='website'><%= link_to @activity.website, @activity.website, target: '_blank' %></span>
              </p>
              <p class="activity-info-text">
                <strong>Description:</strong>
                <span class='description'><%= @activity.description %></span>
              </p>
              <p class="activity-info-text">
                <strong>When:</strong>
                <span class='next_at'><%= @activity.next_at.try(:strftime, "%B %-d, %Y | %l:%M %P") %></span>
              </p>
              <p class="activity-info-text">
                <strong>Schedule:</strong>
                <span class='schedule'><%= @activity.schedule %></span>
              </p>
              <p class="activity-info-text">
                <strong>Contact:</strong>
                <a href='mailto:<%= @activity.organizer_email %>'><%= @activity.organizer_email %></a>
              </p>
            </div>
          </div>
        </div>
    <div class="col-sm-1"></div>
  </div>

    <div class="row">
      <div class="col-sm-1"></div>
        <div class="col-sm-10">
          <p>
            <% if current_user.id == @activity.user_id %>
              <%= link_to 'Edit Activity Details', edit_activity_path(@activity), class: "lg-link" %> |
            <% end %>
            <%= link_to 'Back To Home Page', activities_path, class: "lg-link" %>
          </p>
        </div>
      <div class="col-sm-1"></div>
    </div>

  <div class="row activitymap">
    <div class="col-sm-1"></div>
      <div class="col-sm-10">
        <div id="activity_map" data-activity-id="<%= @activity.id %>">Google Map will Appear Here</div>
      </div>
    <div class="col-sm-1"></div>
  </div>

  <% if current_user.id == @activity.user_id %>
  <div class="row participant-row">
    <div class="col-sm-4"></div>
      <div class="col-sm-4" id="participant_list">
        <h3>Participants In Your Activity</h3>
        <div class="col-sm-12 participant-table">
          <table>
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>Email</th>
              </tr>
            </thead>

            <tbody>
              <% @participant.each do |participant| %>
                <tr>
                  <td>
                    <% unless participant.image.blank? %>
                      <img class="participant_image" src="<%= participant.image %>" alt="">
                    <% end %>
                  </td>
                  <td><%= participant.first_name %></td>
                  <td><%= participant.email %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <% end %>
      </div>
    <div class="col-sm-4"></div>
  </div>

  <div class="row">
    <div class="col-sm-1"></div>
    <div class="col-sm-10">
      <p>
        <p>
          <%= link_to 'Back To Home Page', activities_path, class: "lg-link" %>
        </p>
      </p>
    </div>
    <div class="col-sm-1"></div>
  </div>
</div>